version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17.3

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Clear cache
          command: npm cache clean --force
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: List installed packages
          command: npm list --depth=0
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - .

  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: npm install
          when: always
      - run:
          name: List installed packages
          command: npm list --depth=0
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: npm install
          when: always
      - run:
          name: List installed packages
          command: npm list --depth=0
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  test-branch:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
      - build:
          requires:
            - test
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
